apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: dev
data:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: foyer_db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: dev
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          envFrom:
            - configMapRef:
                name: db-config
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service
  namespace: dev
spec:
  ports:
    - port: 3306
  selector:
    app: mysqldb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-foyer
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-foyer
  template:
    metadata:
      labels:
        app: app-foyer
    spec:
      containers:
        - name: app-foyer
          image: lou4y/tp-foyer-bloc:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysqldb-service:3306/foyer_db?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              value: com.mysql.cj.jdbc.Driver
            - name: SPRING_JPA_HIBERNATE_DDL-AUTO
              value: update
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.MySQLDialect
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: app-foyer-service
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 8082
      nodePort: 30002
  selector:
    app: app-foyer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: lou4y/bloc-frontend-dev:latest
          env:
            - name: API_URL
              value: http://app-foyer-service:8082/tpfoyer/bloc
          ports:
            - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 4200
      nodePort: 30000
  selector:
    app: frontend
